# Test the real process boundary: stdout must contain only one parseable response.
function(expect_success response expected_distance expected_count expected_attenuation)
    string(JSON status GET "${response}" status)
    string(JSON version GET "${response}" schema_version)
    string(JSON distance GET "${response}" geometry links 0 distance)
    string(JSON count GET "${response}" geometry links 0 walls_crossed)
    string(JSON attenuation GET "${response}" geometry links 0 wall_attenuation_db)
    if(NOT status STREQUAL "ok" OR NOT version STREQUAL "1.0"
       OR NOT distance EQUAL expected_distance OR NOT count EQUAL expected_count
       OR NOT attenuation EQUAL expected_attenuation)
        message(FATAL_ERROR "Unexpected CLI result: ${response}")
    endif()
endfunction()
set(names basic single_wall multiple_walls no_intersection same_position)
set(distances 5 5 5 5 0)
set(counts 0 1 2 0 0)
set(attenuations 0 12 17 0 0)
foreach(i RANGE 0 4)
    list(GET names ${i} name)
    list(GET distances ${i} distance)
    list(GET counts ${i} count)
    list(GET attenuations ${i} attenuation)
    execute_process(COMMAND "${SIMULATOR}" "${FIXTURES}/${name}.json"
        RESULT_VARIABLE result OUTPUT_VARIABLE response ERROR_VARIABLE diagnostic)
    if(NOT result EQUAL 0 OR NOT diagnostic STREQUAL "")
        message(FATAL_ERROR "File CLI failed: ${result} ${diagnostic}")
    endif()
    expect_success("${response}" ${distance} ${count} ${attenuation})
endforeach()
execute_process(COMMAND "${SIMULATOR}" INPUT_FILE "${FIXTURES}/basic.json"
    RESULT_VARIABLE result OUTPUT_VARIABLE response ERROR_VARIABLE diagnostic)
if(NOT result EQUAL 0 OR NOT diagnostic STREQUAL "")
    message(FATAL_ERROR "Stdin CLI failed: ${result} ${diagnostic}")
endif()
expect_success("${response}" 5 0 0)

foreach(kind malformed missing unsupported boolean trailing)
    set(input "${CMAKE_CURRENT_BINARY_DIR}/cli_${kind}.json")
    if(kind STREQUAL "malformed")
        file(WRITE "${input}" "{")
    elseif(kind STREQUAL "missing")
        file(WRITE "${input}" "{\"schema_version\":\"1.0\"}")
    elseif(kind STREQUAL "unsupported")
        file(READ "${FIXTURES}/basic.json" bad)
        string(JSON bad SET "${bad}" schema_version "\"2.0\"")
        file(WRITE "${input}" "${bad}")
    elseif(kind STREQUAL "boolean")
        file(READ "${FIXTURES}/basic.json" bad)
        string(JSON bad SET "${bad}" gateways 0 active "1")
        file(WRITE "${input}" "${bad}")
    else()
        file(READ "${FIXTURES}/basic.json" bad)
        file(WRITE "${input}" "${bad} {}")
    endif()
    execute_process(COMMAND "${SIMULATOR}" INPUT_FILE "${input}"
        RESULT_VARIABLE result OUTPUT_VARIABLE response ERROR_VARIABLE diagnostic)
    string(JSON status GET "${response}" status)
    string(JSON code GET "${response}" error code)
    string(JSON detail GET "${response}" error message)
    if(NOT result EQUAL 1 OR NOT status STREQUAL "error" OR NOT code STREQUAL "INVALID_INPUT"
       OR diagnostic STREQUAL "" OR detail STREQUAL "")
        message(FATAL_ERROR "Invalid CLI error response: ${result} ${response} ${diagnostic}")
    endif()
endforeach()
# Missing file and invalid argument count must obey the same process contract.
foreach(args IN ITEMS "${CMAKE_CURRENT_BINARY_DIR}/does-not-exist.json" "one;two")
    execute_process(COMMAND "${SIMULATOR}" ${args}
        RESULT_VARIABLE result OUTPUT_VARIABLE response ERROR_VARIABLE diagnostic)
    string(JSON code GET "${response}" error code)
    if(NOT result EQUAL 1 OR NOT code STREQUAL "INVALID_INPUT")
        message(FATAL_ERROR "CLI usage error contract failed")
    endif()
endforeach()
message(STATUS "CLI file, stdin, stdout/stderr and error contract checks passed")
